[package]
name = "struct_data"
version = "0.1.0"
authors = ["ryotaro <ryo.ex3991@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
